# Generated by Django 3.0.5 on 2020-05-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('union_flid', models.CharField(editable=False, max_length=11, primary_key=True, serialize=False)),
                ('union_geocode', models.CharField(max_length=4)),
                ('union_geocode_old', models.CharField(blank=True, max_length=2, null=True)),
                ('union_name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('union_name_bn', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zila',
            fields=[
                ('zila_flid', models.CharField(editable=False, max_length=4, primary_key=True, serialize=False)),
                ('zila_geocode', models.CharField(max_length=2)),
                ('division_geocode', models.CharField(max_length=2)),
                ('zila_name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('zila_name_bn', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_flid', models.CharField(editable=False, max_length=17, primary_key=True, serialize=False)),
                ('village_geocode', models.CharField(max_length=3)),
                ('village_geocode_old', models.CharField(max_length=3)),
                ('village_name_en', models.CharField(max_length=30)),
                ('village_name_bn', models.CharField(blank=True, max_length=30, null=True)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.Union')),
            ],
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('upazila_flid', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('upazila_geocode', models.CharField(max_length=3)),
                ('upazila_name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('upazila_name_bn', models.CharField(blank=True, max_length=30, null=True)),
                ('zila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.Zila')),
            ],
        ),
        migrations.AddField(
            model_name='union',
            name='upazila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.Upazila'),
        ),
        migrations.CreateModel(
            name='Mouja',
            fields=[
                ('mouja_flid', models.CharField(editable=False, max_length=14, primary_key=True, serialize=False)),
                ('jl_no', models.CharField(blank=True, max_length=3, null=True)),
                ('mouja_geocode', models.CharField(max_length=3)),
                ('mouja_geocode_old', models.CharField(blank=True, max_length=3, null=True)),
                ('mouja_name_en', models.CharField(blank=True, max_length=30, null=True)),
                ('mouja_name_bn', models.CharField(blank=True, max_length=30, null=True)),
                ('total_area_of_land', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgd.Union')),
            ],
        ),
    ]
