# Generated by Django 3.0.5 on 2020-05-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lgd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='moujav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lgd.Mouja'),
        ),
    ]
