# Generated by Django 3.0.5 on 2020-05-15 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lgd', '0002_village_moujav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouja',
            name='total_area_of_land',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='moujav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lgd.Mouja', verbose_name='Mouja'),
        ),
    ]
