# Generated by Django 3.0.5 on 2020-05-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgd', '0003_auto_20200515_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='union_name_bn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='union name (Bn)'),
        ),
        migrations.AlterField(
            model_name='union',
            name='union_name_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='union name (En)'),
        ),
    ]
